#!/usr/bin/env python
# vim: set expandtab tabstop=4 shiftwidth=4:

# Copyright (c) 2019, CJ Kucera
# All rights reserved.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are met:
#     * Redistributions of source code must retain the above copyright
#       notice, this list of conditions and the following disclaimer.
#     * Redistributions in binary form must reproduce the above copyright
#       notice, this list of conditions and the following disclaimer in the
#       documentation and/or other materials provided with the distribution.
#     * Neither the name of the development team nor the
#       names of its contributors may be used to endorse or promote products
#       derived from this software without specific prior written permission.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
# ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
# WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
# DISCLAIMED. IN NO EVENT SHALL CJ KUCERA BE LIABLE FOR ANY
# DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
# (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
# LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
# ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
# (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
# SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

import sys

try:
    from modprocessor import ModProcessor
    mp = ModProcessor()
except ModuleNotFoundError:
    print('')
    print('********************************************************************')
    print('To run this script, you will need to copy or symlink modprocessor.py')
    print('from the parent directory, so it exists here as well.  Sorry for')
    print('the bother!')
    print('********************************************************************')
    print('')
    sys.exit(1)

try:
    from ftexplorer.data import Data
except ModuleNotFoundError:
    print('')
    print('****************************************************************')
    print('To run this script, you will need to copy or symlink the')
    print('"ftexplorer" and "resources" dirs from my ft-explorer project so')
    print('they exist here as well.  Sorry for the bother!')
    print('****************************************************************')
    print('')
    sys.exit(1)

# Control Vars
mod_name = 'Red Text Explainer'
mod_version = '1.1.0'
output_filename = '{}.blcm'.format(mod_name)
explanation_color = '#5ff5ff'
data = Data('BL2')
DESC = 'Description'
NOC = 'NoConstraintText'
valid_attrs = { DESC, NOC }
ON_CARD = 'All effects listed.'

# Item lists
mod_items = [
    ('ARs', NOC, {
        'Pearlescent': [
            ("Bearcat",
                "GD_Gladiolus_Weapons.Name.Title.Title_Pearlescent_Bearcat:AttributePresentationDefinition_8",
                "Fire 3 grenades per shot, chance to spawn child grenades.",
                None,
                None,
                ),
            ("Bekah",
                "GD_Lobelia_Weapons.Name.Title.Title_Pearlescent_Bekah:AttributePresentationDefinition_8",
                "Fires 1 projectiles which splits in 4.",
                None,
                None,
                ),
            ("Sawbar",
                "GD_Gladiolus_Weapons.Name.Title.Title_Pearlescent_Sawbar:AttributePresentationDefinition_8",
                "Always fire, shots fired spawn three other projectiles that travel out at an angle before exploding.",
                None,
                None,
                ),
            ],
        'Seraph': [
            ("Lead storm",
                "GD_Sage_RaidWeapons.Name.Title.Sage_Seraph_LeadStorm_Title:AttributePresentationDefinition_8",
                "Fires flared, slow-arcing bullets, which split into three projectiles during travel with small critical bonus damage.",
                None,
                None,
                ),
            ("Seraphim",
                "GD_Orchid_RaidWeapons.AssaultRifle.Seraphim.Orchid_Seraph_Seraphim_Title:AttributePresentationDefinition_8",
                "Fires large, slow-moving projectiles. Always incendiary.",
                None,
                None,
                ),
            ("Seeker",
                "GD_Aster_RaidWeapons.AssaultRifles.Aster_Seraph_Seeker_Title:AttributePresentationDefinition_8",
                "2 ammo per shot, fire chasing bullets.",
                None,
                None,
                ),
            ],
        'Uniques': [
            ("Damned Cowboy",
                "GD_Sage_Weapons.Name.Title.Title_Unique_DamnedCowboy:AttributePresentationDefinition_8",
                "+55% Critical Hit Damage.",
                None,
                None,
                ),
            ("Boom Puppy",
                "GD_Iris_Weapons.Name.Title.Title_Unique_BoomPuppy:AttributePresentationDefinition_8",
                "Fires a low velocity, rubberized bouncing grenade which explodes each time it bounces.",
                None,
                None,
                ),
            ("Scorpio",
                "GD_Weap_AssaultRifle.Name.Title.Title_Unique_Scorpio:AttributePresentationDefinition_8",
                "Variable burst-fire count when zoomed. Variable fire rate when hip fire.",
                None,
                None,
                ),
            ("Evil Smasher",
                "GD_Weap_AssaultRifle.Name.Title.Title_Unique_EvilSmasher:AttributePresentationDefinition_8",
                "Reloading has a small chance to massively enhance the power of the weapon and will last until the next reload.",
                None,
                None,
                ),
            ("CHOPPER",
                "GD_Sage_Weapons.Name.Title.Title_Unique_Chopper:AttributePresentationDefinition_8",
                "Extremely fast fire rate and low accuracy. Fire the whole magasine at one trigger press.",
                None,
                None,
                ),
            ("Stinkpot",
                "GD_Orchid_BossWeapons.Name.Title.Title__Unique_Stinkpot:AttributePresentationDefinition_8",
                "Always corrosive, Large splash effect. Corrosive damage spreads to other enemies.",
                None,
                None,
                ),
            ("Rapier",
                "GD_Orchid_BossWeapons.Name.Title.Title__Unique_Cutlass:AttributePresentationDefinition_0",
                "The user takes increased damage from Melee attacks.",
                None,
                None,
                ),
            ("Stomper",
                "GD_Weap_AssaultRifle.Name.Title_Jakobs.Title_Unique_Stomper:AttributePresentationDefinition_8",
                "High crit damage.",
                None,
                None,
                ),
            ],
        'Legendary': [
            ("KerBlaster",
                "GD_Weap_AssaultRifle.Name.Title_Torgue.Title_Legendary_KerBlaster:AttributePresentationDefinition_8",
                "4 ammo per shot, cannont crit, boosted by Grenade damages.",
                None,
                None,
                ),
            ("Veruc",
                "GD_Weap_AssaultRifle.Name.Title_Dahl.Title_Legendary_Veruc:AttributePresentationDefinition_8",
                "Fires 3 projectiles in linear spread. 5-round burst when zoomed with tightened spread.",
                None,
                None,
                ),
            ("Hammer Buster",
                "GD_Weap_AssaultRifle.Name.Title_Jakobs.Title_Legendary_HammerBuster:AttributePresentationDefinition_8",
                "Increased damage and critical hit bonus.",
                None,
                None,
                ),
            ("Ogre",
                "GD_Aster_Weapons.Name.Title.Title_Unique_Ogre:AttributePresentationDefinition_8",
                "100% extra splash damage. Chance to receive buff to increase fire rate, reload speed. During buff, bullets ricochet.",
                None,
                None,
                ),
            ("Madhous!",
                "GD_Weap_AssaultRifle.Name.Title_Bandit.Title_Legendary_Madhouse:AttributePresentationDefinition_8",
                "Bullets will follow a random slightly swerving path, then will split on impact and bounce.",
                None,
                None,
                ),
            ("Shredifier",
                "GD_Weap_AssaultRifle.Name.Title_Vladof.Title_Legendary_Shredifier:AttributePresentationDefinition_8",
                "Greatly decreased spool time, extremely high firing speed and very large capacity. Slightly reduced damage.",
                None,
                None,
                ),
            ("M2828 Thompson",
                "GD_Anemone_Weapons.AssaultRifle.Brothers.Title_Legendary_Brothers:AttributePresentationDefinition_8",
                "Increased damage, critical hit bonus and magazine size",
                None,
                None,
                ),
            ],
        'Moxxi': [
            ("Hail",
                "GD_Weap_AssaultRifle.Name.Title.Title_Unique_Hail:AttributePresentationDefinition_8",
                "3% lifesteal, 200% bonus crit damage. Always elemental, fires projectiles in an arc.",
                None,
                None,
                ),
            ("Kitten",
                "GD_Iris_Weapons.Name.Title.Title_Unique_Kitten:AttributePresentationDefinition_8",
                "4% lifesteal, 3 bullets per shot. Pattern forms a smiley face.",
                None,
                None,
                ),
            ],
        'Effervescent': [
            ("Peak opener",
                "GD_Anemone_Weapons.AssaultRifle.PeakOpener.Title_Effervescent_PeakOpener:AttributePresentationDefinition_8",
                "Fires rockets that drop 3 child grenades on impact. Child grenades deal explosive damage.",
                None,
                None,
                ),
            ("Toothpick",
                "GD_Anemone_Weapons.AssaultRifle.Title_Effervescent_Worming:AttributePresentationDefinition_8",
                "Always incendiary. Fires 10 shots in 2 rows of 5.",
                None,
                None,
                ),
            ],
        }),
    ('Pistols', NOC, {
        'Pearlescent': [
            ("Stalker",
                "GD_Gladiolus_Weapons.Name.Title.Title_Pearlescent_Stalker:AttributePresentationDefinition_8",
                "Significantly increased damage, reload speed, rate of fire and capacity at the cost of accuracy, bullet ricochet 5 times.",
                None,
                None,
                ),
            ("Unforgiven",
                "GD_Gladiolus_Weapons.Name.Title.Title_Pearlescent_Unforgiven:AttributePresentationDefinition_8",
                "+100% additive critical damage and +25% multiplicative crit damage",
                None,
                None,
                ),
            ("Wanderlust",
                "GD_Lobelia_Weapons.Name.Title.Title_Pearlescent_Wanderlust:AttributePresentationDefinition_8",
                "Fires ricocheting homing darts, increase elemental chances at the cost of projectile damage.",
                None,
                None,
                ),
            ],
        'Seraph': [
            ("Infection",
                "GD_Sage_RaidWeapons.Name.Title.Sage_Seraph_Infection_Title:AttributePresentationDefinition_8",
                "Always corrosive, extremely high elemental effect damage and chance.",
                None,
                None,
                ),
            ("Stinger",
                "GD_Aster_RaidWeapons.Pistols.Aster_Seraph_Stinger_Title:AttributePresentationDefinition_8",
                "Ricocheting bullets. Additive 15% critical hit bonus.",
                None,
                None,
                ),
            ("Devastator",
                "GD_Orchid_RaidWeapons.Pistol.Devastator.Orchid_Seraph_Devastator_Title:AttributePresentationDefinition_8",
                "Increased damage, two-round burst. Decreased bullet velocity.",
                None,
                None,
                ),
            ],
        'Unique': [
            ("Tinderbox",
                "GD_Weap_Pistol.Name.Title.Title__Unique_Tinderbox:AttributePresentationDefinition_8",
                "Good for starting fires, +100% splash damage.",
                None,
                None,
                ),
            ("Dahlminator",
                "GD_Weap_Pistol.Name.Title.Title__Unique_Dahlminator:AttributePresentationDefinition_8",
                "Always corrosive, fires slow-moving, homing projectiles.",
                None,
                None,
                ),
            ("Fibber (remove global red text)",
                "GD_Weap_Pistol.Name.Title.Title__Unique_Fibber:AttributePresentationDefinition_8",
                "",
                0,
                "",
                ),
            ("Fibber #1",
                "GD_Weap_Pistol.Barrel.Fibber.Pistol_Barrel_Bandit_Fibber_1:AttributePresentationDefinition_1",
                "Low-velocity shotgun.",
                20,
                "<font color=\"#DC4646\">Would I lie to you?</font>",
                ),
            ("Fibber #2",
                "GD_Weap_Pistol.Barrel.Fibber.Pistol_Barrel_Bandit_Fibber_2:AttributePresentationDefinition_1",
                "Full-speed ricochet on impact or wall hit.",
                20,
                "<font color=\"#DC4646\">Would I lie to you?</font>",
                ),
            ("Fibber #3",
                "GD_Weap_Pistol.Barrel.Fibber.Pistol_Barrel_Bandit_Fibber_3:AttributePresentationDefinition_1",
                "Arcing projectiles with 700% crit bonus.",
                20,
                "<font color=\"#DC4646\">Would I lie to you?</font>",
                ),
            ("Gwen's Head",
                "GD_Weap_Pistol.Name.Title.Title__Unique_GwensHead:AttributePresentationDefinition_8",
                "7 round burst when zoomed.",
                None,
                None,
                ),
            ("Greed",
                "GD_Orchid_BossWeapons.Name.Title.Title__Unique_ScarletsGreed:AttributePresentationDefinition_8",
                "Always fire. No movement speed penalty when aiming.",
                None,
                None,
                ),
            ("Law",
                "GD_Weap_Pistol.Name.Title.Title__Unique_Law:AttributePresentationDefinition_8",
                "Always melee +100%, if the Order is equipped, melee attacks with Law will restore 25% of the damage dealt.",
                None,
                None,
                ),
            ("Little Evie",
                "GD_Orchid_BossWeapons.Name.Title.Title__Unique_LittleEvie:AttributePresentationDefinition_8",
                "Always shock, Killing an enemy increases action skill cooldown rate by 12%.",
                None,
                None,
                ),
            ("Judge",
                "GD_Weap_Pistol.Name.Title.Title__Unique_Judge:AttributePresentationDefinition_8",
                "Bonus critical hit damage: +30% additive and +15% multiplicative.",
                None,
                None,
                ),
            ("Lady fist",
                "GD_Weap_Pistol.Name.Title.Title__Unique_LadyFist:AttributePresentationDefinition_8",
                "Decreased bullet damage. Increased accuracy and magazine size but +800% Crit damage.",
                None,
                None,
                ),
            ("Pocket Rocket",
                "GD_Iris_Weapons.Name.Title.Title_Unique_PocketRocket:AttributePresentationDefinition_8",
                "Icreased overall stats, 2ammo per shot.",
                None,
                None,
                ),
            ("Teapot",
                "GD_Weap_Pistol.Name.Title.Title__Unique_Teapot:AttributePresentationDefinition_8",
                "Always corrosive, Increase elemental Damage and accuracy at the cost of damage, fire rate, mag size and elem chance.",
                None,
                None,
                ),
            ("Rex",
                "GD_Sage_Weapons.Name.Title.Title_Unique_Rex:AttributePresentationDefinition_8",
                "+40% critical hit damage at the cost of low fire rate for a jakobs pistol.",
                None,
                None,
                ),
            ],
        'Legendary': [
            ("Infinity",
                "GD_Weap_Pistol.Name.Title_Vladof.Title_Legendary_Infinity:AttributePresentationDefinition_8",
                "Does not consume ammunition, fire in an infinity shape.",
                None,
                None,
                ),
            ("Thunderball Fists",
                "GD_Weap_Pistol.Name.Title_Maliwan.Title_Legendary_ThunderballFists:AttributePresentationDefinition_8",
                "Always Shock, fire a projectile that flare upwards for a short distance then detonating a second time.",
                None,
                None,
                ),
            ("Maggie",
                "GD_Weap_Pistol.Name.Title_Jakobs.Title_Legendary_Maggie:AttributePresentationDefinition_8",
                "Fires 6 projectiles at the cost of 1 ammo, with decreased accuracy and damage per projectile.",
                None,
                None,
                ),
            ("Gub",
                "GD_Weap_Pistol.Name.Title_Bandit.Title_Legendary_Gub:AttributePresentationDefinition_8",
                "Massive magazine, heavily increased damage, always corrosive.",
                None,
                None,
                ),
            ("Hornet",
                "GD_Weap_Pistol.Name.Title_Dahl.Title_Legendary_Hornet:AttributePresentationDefinition_8",
                "Always corrosive. 6 round burst when aiming. Projectiles do slight area of effect.",
                None,
                None,
                ),
            ("Unkempt Harold",
                "GD_Weap_Pistol.Name.Title_Torgue.Title_Legendary_Calla:AttributePresentationDefinition_8",
                "Fires 7 shots in an accelerating horizontal spread at the cost of 3 ammo per shot.",
                None,
                None,
                ),
            ("Veritas",
                "GD_Weap_Pistol.Name.Title.Title__Unique_Veritas:AttributePresentationDefinition_8",
                "+10% FFYL time for every Veritas or Aequitas equipped in the party. Also comes with a 10% crit bonus damage.",
                None,
                None,
                ),
            ("Gunerang",
                "GD_Weap_Pistol.Name.Title_Tediore.Title_Legendary_Gunerang:AttributePresentationDefinition_8",
                "Unique boomerang reload with bonus reload damage on the return.",
                None,
                None,
                ),
            ("Logan's gun",
                "GD_Weap_Pistol.Name.Title_Hyperion.Title_Legendary_LogansGun:AttributePresentationDefinition_8",
                "Always incendiary, Bullet explode on contact then explode a second time after a small delay. Bullets are considered as Rockets.",
                None,
                None,
                ),
            ("Hector's Paradise",
                "GD_Anemone_Weapons.Name.Title_Dahl.Title_Legendary_Hornet_Hector:AttributePresentationDefinition_8",
                "Always shock. Have splash damage. Six-round burst-fire while zoomed. Always Bladed.",
                None,
                None,
                ),
            ],
        'Moxxi': [
            ("Grog Nozzle",
                "GD_Aster_Weapons.Name.Title.Title__Unique_GrogNozzle:AttributePresentationDefinition_8",
                "Lifesteal of 65%.",
                None,
                None,
                ),
            ("Rubi",
                "GD_Weap_Pistol.Name.Title.Title__Unique_Rubi:AttributePresentationDefinition_8",
                "12% Lifesteal to all damage source.",
                None,
                None,
                ),
            ],
        'Effervescent': [
            ("Fire Drill",
                "GD_Anemone_Weapons.Name.Title.Title_DroletDrill:AttributePresentationDefinition_8",
                "Does not consume ammunition, fire in an infinity shape, 100% Fire DOT, high damage.",
                None,
                None,
                ),
            ],
        }),
    ('Rocket Launchers', NOC, {
        'Pearlescent': [
            ("Tunguska",
                "GD_Gladiolus_Weapons.Name.Title.Title_Pearlescent_Tunguska:AttributePresentationDefinition_8",
                "Fires in a parabolic arc similar to a mortar, rise a few feet into the air, and explode.",
                None,
                None,
                ),
            ],
        'Seraph': [
            ("Ahab",
                "GD_Orchid_RaidWeapons.RPG.Ahab.Orchid_Seraph_Ahab_Title:AttributePresentationDefinition_8",
                "Shoots harpoon projectile that sticks before exploding. Deals explosive damage.",
                None,
                None,
                ),
            ],
        'Legendary': [
            ("Badaboom",
                "GD_Weap_Launchers.Name.Title_Bandit.Title_Legendary_Badaboom:AttributePresentationDefinition_8",
                "Fires 6 rockets at cost of 1. Reduced damage and accuracy.",
                None,
                None,
                ),
            ("Mongol",
                "GD_Weap_Launchers.Name.Title_Vladof.Title_Legendary_Mongol:AttributePresentationDefinition_8",
                "Fires a single large rocket that sporadically releases multiple smaller rockets at random angles.",
                None,
                None,
                ),
            ("Nukem",
                "GD_Weap_Launchers.Name.Title_Torgue.Title_Legendary_Nukem:AttributePresentationDefinition_8",
                "Rockets fly in an arc and explode in a mushroom cloud.",
                None,
                None,
                ),
            ("Bunny",
                "GD_Weap_Launchers.Name.Title_Tediore.Title_Legendary_Bunny:AttributePresentationDefinition_8",
                "When reloaded it drops out active grenades at random while bouncing like a rabbit.",
                None,
                None,
                ),
            ("Norfleet",
                "GD_Weap_Launchers.Name.Title_Maliwan.Title_Barrel_Maliwan_Norfleet:AttributePresentationDefinition_8",
                "Fires three large purple projectiles in a horizontal line with erratic trajectory, large damage and blast radius.",
                None,
                None,
                ),
            ("Pyrophobia",
                "GD_Weap_Launchers.Name.Title_Maliwan.Title_Legendary_Pyrophobia:AttributePresentationDefinition_8",
                "Always Incendiary. Projectiles explode multiple times mid-flight before hitting their target.",
                None,
                None,
                ),
            ],
        'Moxxi': [
            ("Creamer",
                "GD_Weap_Launchers.Name.Title.Title__Unique_Creamer:AttributePresentationDefinition_8",
                "2% lifesteal. High velocity. Will split in 2 after certain distance.",
                None,
                None,
                ),
            ],
        'Uniques': [
            ("Roaster",
                "GD_Weap_Launchers.Name.Title.Title__Unique_Roaster:AttributePresentationDefinition_8",
                "Increased elemental chance, status effect damage, and accuracy. Slightly decreased base damage.",
                None,
                None,
                ),
            ("Hive",
                "GD_Weap_Launchers.Name.Title.Title__Unique_TheHive:AttributePresentationDefinition_8",
                "4 ammo per shot. Fires a hive that released homing corrosive rockets.",
                None,
                None,
                ),
            ("12 Pounder",
                "GD_Orchid_BossWeapons.Name.Title.Title__Unique_12Pounder:AttributePresentationDefinition_8",
                "Fires a cannonball that can crit and ricochet.",
                None,
                None,
                ),
            ],
        'Effervesscent': [
            ("World Burn",
                "GD_Anemone_Weapons.Rocket_Launcher.WorldBurn.Title_Effervescent_WorldBurn:AttributePresentationDefinition_8",
                "Always incendiary. Rockets fly in an arc and explode in a mushroom cloud.",
                None,
                None,
                ),
            ],
        }),
    ('SMGs', NOC, {
        'Pearlescent': [
            ("Avenger",
                "GD_Gladiolus_Weapons.Name.Title.Title_Pearlescent_Avenger:AttributePresentationDefinition_8",
                "Behaves like bouncing betty grenade on reload. Increased ammo regen.",
                None,
                None,
                ),
            ],
        'Seraph': [
            ("Actualizer",
                "GD_Orchid_RaidWeapons.SMG.Actualizer.Orchid_Seraph_Actualizer_Title:AttributePresentationDefinition_8",
                "Increased damage. Decreased projectile speed. Expanded magazine size. Extended reload time.",
                None,
                None,
                ),
            ("Florentine",
                "GD_Aster_RaidWeapons.SMGs.Aster_Seraph_Florentine_Title:AttributePresentationDefinition_8",
                "Shock projectile, bonus slag damage on impact.",
                None,
                None,
                ),
            ("Tattler",
                "GD_Orchid_RaidWeapons.SMG.Tattler.Orchid_Seraph_Tattler_Title:AttributePresentationDefinition_8",
                "Always bladed. Fires three slow-moving projectiles at the cost of one ammo.",
                None,
                None,
                ),
            ],
        'Legendary': [
            ("Baby Maker",
                "GD_Weap_SMG.Name.Title_Tediore.Title_Legendary_BabyMaker:AttributePresentationDefinition_8",
                "Thrown weapon spawns child grenades upon exploding, a smaller version that explodes again up to 3 total child grenade.",
                None,
                None,
                ),
            ("Slagga",
                "GD_Weap_SMG.Name.Title_Bandit.Title_Legendary_Slagga:AttributePresentationDefinition_8",
                "Increased chance to slag. No damage to already slagged enemies.",
                None,
                None,
                ),
            ("HellFire",
                "GD_Weap_SMG.Name.Title_Maliwan.Title_Legendary_HellFire:AttributePresentationDefinition_8",
                "Always incendiary. Increased elemental effect chance, effect damage, and magazine size. 50% splash damage.",
                None,
                None,
                ),
            ("Emperor",
                "GD_Weap_SMG.Name.Title.Title_Legendary_Dahl_Emperor:AttributePresentationDefinition_8",
                "Fires a 6-round burst, 7 if the gun stock is Dahl",
                None,
                None,
                ),
            ("Bitch",
                "GD_Weap_SMG.Name.Title_Hyperion.Title_Legendary_Bitch:AttributePresentationDefinition_8",
                "Increased accuracy, magazine size and critical hit damage.",
                None,
                None,
                ),
            ],
        'Uniques': [
            ("Bane",
                "GD_Weap_SMG.Name.Title.Title__Unique_Bane:AttributePresentationDefinition_8",
                "-500% movement speed. Scream at you to death.",
                None,
                None,
                ),
            ("Orc",
                "GD_Aster_Weapons.Name.Title.Title_Unique_Orc:AttributePresentationDefinition_8",
                "Chance to buff self. On buff, bullets ricochet and split in 3.",
                None,
                None,
                ),
            ("Commerce",
                "GD_Weap_SMG.Name.Title.Title__Unique_Commerce:AttributePresentationDefinition_8",
                "Always shock.",
                None,
                None,
                ),
            ("Bone Shredder",
                "GD_Weap_SMG.Name.Title.Title__Unique_BoneShredder:AttributePresentationDefinition_8",
                "Increased damage and magazine size.",
                None,
                None,
                ),
            ("Chulainn",
                "GD_Weap_SMG.Name.Title.Title__Unique_Chulainn:AttributePresentationDefinition_8",
                "Fires shock rounds which also do bonus slag damage. Applies slag to the wielder as long as the weapon is equipped.",
                None,
                None,
                ),
            ("Yellow Jacket",
                "GD_Sage_Weapons.Name.Title.Title_Unique_YellowJacket:AttributePresentationDefinition_8",
                "Always shock, Projectiles accelerate and bounce off the first surface it hits and have a small blast radius.",
                None,
                None,
                ),
            ("Sandhawk",
                "GD_Orchid_BossWeapons.Name.Title.Title__Unique_SandHawk:AttributePresentationDefinition_8",
                "Consumes three rounds per shot, producing 8 slow-moving projectiles in a horizontal bird-shaped pattern",
                None,
                None,
                ),
            ("Lascaux",
                "GD_Weap_SMG.Name.Title.Title__Unique_Lascaux:AttributePresentationDefinition_8",
                "Very high, variable burst-fire count, fire in a Lascaux pattern.",
                None,
                None,
                ),
            ],
        'Moxxi': [
            ("Bad Touch",
                "GD_Weap_SMG.Name.Title.Title__Unique_BadTouch:AttributePresentationDefinition_8",
                "2% lifesteal. Always corrosive. +70% crit damage.",
                None,
                None,
                ),
            ("Crit",
                "GD_Aster_Weapons.Name.Title.Title__Unique_Crit:AttributePresentationDefinition_8",
                "12% chance to be dropped when reloaded, 2.5% lifesteal. +150% bonus crit damage.",
                None,
                None,
                ),
            ("Good Touch",
                "GD_Weap_SMG.Name.Title.Title__Unique_GoodTouch:AttributePresentationDefinition_8",
                "2.5% lifesteal. Always fire. +70% crit damage.",
                None,
                None,
                ),
            ],
        'Effervescent': [
            ("Infection cleaner",
                "GD_Anemone_Weapons.Name.Title.Title_Infection_Cleaner:AttributePresentationDefinition_8",
                "Always incendiary. Increased damage, magazine size and critical hit damage. Behaves like a Bouncing Betty Grenade when reloaded, regen ammo while wielded.",
                None,
                None,
                ),
            ("Nirvana",
                "GD_Anemone_Weapons.Name.Title.Title_LaTiteVierge:AttributePresentationDefinition_8",
                "Always incendiary. 50% elemental splash damage.",
                None,
                None,
                ),
            ],
        }),
    ('Shotguns', NOC, {
        'Pearlescent': [
            ("Butcher",
                "GD_Gladiolus_Weapons.Name.Title.Title_Pearlescent_Butcher:AttributePresentationDefinition_8",
                "Magazine randomly refills amount when fired. Fire rate increases when held.",
                None,
                None,
                ),
            ("Carnage",
                "GD_Lobelia_Weapons.Name.Title.Title_Pearlescent_Carnage:AttributePresentationDefinition_8",
                "Massive damage increase. Reduce pellet count. Larger area of effect radius.",
                None,
                None,
                ),
            ],
        'Seraph': [
            ("Interfacer",
                "GD_Sage_RaidWeapons.Name.Title.Sage_Seraph_Interfacer_Title:AttributePresentationDefinition_8",
                "Fires slow moving projectiles that spawn 2 additional ones horizontally.",
                None,
                None,
                ),
            ("Omen",
                "GD_Aster_RaidWeapons.Shotguns.Aster_Seraph_Omen_Title:AttributePresentationDefinition_8",
                "Unique firing pattern contracts and expands as it travels.",
                None,
                None,
                ),
            ("Retcher",
                "GD_Orchid_RaidWeapons.Shotgun.Spitter.Orchid_Seraph_Spitter_Title:AttributePresentationDefinition_8",
                "Always corrosive. Projectiles arc. Reloading produces 2 child grenades after initial explosion.",
                None,
                None,
                ),
            ],
        'Uniques': [
            ("Triquetra",
                "GD_Weap_Shotgun.Name.Title.Title__Unique_Triquetra:AttributePresentationDefinition_8",
                "Increased damage and number of pellets. Pellets fire in a Triquetra shape.",
                None,
                None,
                ),
            ("Tidal Wave",
                "GD_Weap_Shotgun.Name.Title.Title__Unique_TidalWave:AttributePresentationDefinition_8",
                "Fires 13 horizontal slow moving projectiles in a wave pattern that ricochets off of surfaces once.",
                None,
                None,
                ),
            ("Shotgun 1340",
                "GD_Weap_Shotgun.Name.Title.Title__Unique_Shotgun1340:AttributePresentationDefinition_8",
                "Have the voice module of loader #1340.",
                None,
                None,
                ),
            ("Teeth of Terra",
                "GD_Weap_Shotgun.Name.Title.Title__Unique_Teeth:AttributePresentationDefinition_8",
                "Always incendiary, fires two horizontal rows of 6 rounds each in a shape of a bite.",
                None,
                None,
                ),
            ("Landscaper",
                "GD_Weap_Shotgun.Name.Title.Title__Unique_Landscaper:AttributePresentationDefinition_8",
                "Fires four small grenade-like projectiles, grenades stick to any surface and explode several seconds after being fired, explode on contact.",
                None,
                None,
                ),
            ("RokSalt",
                "GD_Weap_Shotgun.Name.Title.Title__Unique_RokSalt:AttributePresentationDefinition_8",
                "Increased reload speed, accuracy, damage, and fire rate.",
                None,
                None,
                ),
            ("Octo",
                "GD_Weap_Shotgun.Name.Title.Title__Unique_Octo:AttributePresentationDefinition_8",
                "Fires 10 pellets in a 3x3 grid pattern with the centre left point missing, slow moving and fly in a sine-wave pattern",
                None,
                None,
                ),
            ("Hydra",
                "GD_Sage_Weapons.Name.Title.Title_Unique_Hydra:AttributePresentationDefinition_8",
                "Spread forms five groupings in a horizontal line.",
                None,
                None,
                ),
            ("Dog",
                "GD_Weap_Shotgun.Name.Title.Title__Unique_Dog:AttributePresentationDefinition_8",
                "Increased damage, fire rate and magazine size.",
                None,
                None,
                ),
            ("Jolly Roger",
                "GD_Orchid_BossWeapons.Name.Title.Title__Unique_JollyRoger:AttributePresentationDefinition_8",
                "Fixed Skull and Bones pattern.",
                None,
                None,
                ),
            ("SWORDSPLOSION!!!",
                "GD_Aster_Weapons.Name.Title.Title__Unique_Swordsplosion:AttributePresentationDefinition_8",
                "Swords explodes on impact, spawning 3 swords which also explode.",
                None,
                None,
                ),
            ("Twister",
                "GD_Sage_Weapons.Name.Title.Title_Unique_Twister:AttributePresentationDefinition_8",
                "Shock only. Fire a cluster of pellets that transform into a tornado.",
                None,
                None,
                ),
            ("Blockhead",
                "GD_Weap_Shotgun.Name.Title.Title__Unique_Blockhead:AttributePresentationDefinition_8",
                "Fires in a 3x3 grid that ricochet multiple times. 100% splash damage.",
                None,
                None,
                ),
            ("Orphan Maker",
                "GD_Orchid_BossWeapons.Name.Title.Title__Unique_OrphanMaker:AttributePresentationDefinition_2",
                "Increased damage, reduced pellet count, and damages the player.",
                None,
                None,
                ),
            ],
        'Legendary': [
            ("Flakker",
                "GD_Weap_Shotgun.Name.Title_Torgue.Title_Legendary_Flakker:AttributePresentationDefinition_8",
                "Extremely large spread, rounds detonate after reaching a certain distance.",
                None,
                None,
                ),
            ("Deliverance",
                "GD_Weap_Shotgun.Name.Title_Tediore.Title_Legendary_Deliverance:AttributePresentationDefinition_8",
                "Reload spawns a homing shooting shotguns.",
                None,
                None,
                ),
            ("Striker",
                "GD_Weap_Shotgun.Name.Title_Jakobs.Title_Legendary_Striker:AttributePresentationDefinition_8",
                "50% additive crit bonus and a 15% multiplicative crit bonus.",
                None,
                None,
                ),
            ("Conference call",
                "GD_Weap_Shotgun.Name.Title_Hyperion.Title_Legendary_ConferenceCall:AttributePresentationDefinition_8",
                "Fires 5 projectiles per shot. Each projectile generates additional projectiles upon impact or after sufficient distance.",
                None,
                None,
                ),
            ("Overcompensator",
                "GD_Anemone_Weapons.Shotgun.Overcompensator.Title_Legendary_Overcompensator:AttributePresentationDefinition_8",
                "Magazine randomly refills amount when fired. Reduced pellets.",
                None,
                None,
                ),
            ("Sledge's Shotgun",
                "GD_Weap_Shotgun.Name.Title_Bandit.Title_Legendary_Shotgun:AttributePresentationDefinition_8",
                "Two-shot burst, +2 projectile count.",
                None,
                None,
                ),
            ],
        'Moxxi': [
            ("Slow Hand",
                "GD_Iris_Weapons.Name.Title.Title_Unique_SlowHand:AttributePresentationDefinition_8",
                "3.5% lifesteal. Cannot crit",
                None,
                None,
                ),
            ("Heartbreaker",
                "GD_Weap_Shotgun.Name.Title.Title__Unique_HeartBreaker:AttributePresentationDefinition_8",
                "Always Fire. Increased projectile count, fire rate, +50% critical hit damage bonus. 2% Lifesteal",
                None,
                None,
                ),
            ],
        'Effervescent': [
            ("Unicornsplosion",
                "GD_Anemone_Weapons.Name.Title.Title__Unique_Unicornplosion:AttributePresentationDefinition_8",
                "Fire Butt Stallions and explode into 3 chunks.",
                None,
                None,
                ),
            ],
        }),
    ('Snipers', NOC, {
        'Pearlescent': [
            ("Godfinger",
                "GD_Lobelia_Weapons.Name.Title.Title_Pearlescent_Godfinger:AttributePresentationDefinition_8",
                "Generates new pellets the longer the bullet travels, up to 14x damage.",
                None,
                None,
                ),
            ("Storm",
                "GD_Gladiolus_Weapons.Name.Title.Title_Pearlescent_Storm:AttributePresentationDefinition_8",
                "Always shock. On impact, create electric orbs that shock enemies.",
                None,
                None,
                ),
            ],
        'Seraph': [
            ("Hawk Eye",
                "GD_Sage_RaidWeapons.Name.Title.Sage_Seraph_HawkEye_Title:AttributePresentationDefinition_8",
                "Extremely high crit damage. High zoom, fire rate, reload, mag.",
                None,
                None,
                ),
            ("Patriot",
                "GD_Orchid_RaidWeapons.sniper.Patriot.Orchid_Seraph_Patriot_Title:AttributePresentationDefinition_8",
                "Fires slower-moving projectiles, Large bullet spread.",
                None,
                None,
                ),
            ],
        'Legendary': [
            ("Lyuda",
                "GD_Weap_SniperRifles.Name.Title_Vladof.Title_Legendary_Lyudmila:AttributePresentationDefinition_8",
                "Shoots one projectile that splits into three projectiles after a certain time on a horizontal plane at 75% card damage. Have a 125% base crit bonus.",
                None,
                None,
                ),
            ("Volcano",
                "GD_Weap_SniperRifles.Name.Title_Maliwan.Title_Legendary_Volcano:AttributePresentationDefinition_8",
                "80% splash damage.",
                None,
                None,
                ),
            ("Skullmasher",
                "GD_Weap_SniperRifles.Name.Title_Jakobs.Title_Legendary_Skullmasher:AttributePresentationDefinition_8",
                "x5 projectiles at the cost of 1 ammo.",
                None,
                None,
                ),
            ("Pitchfork",
                "GD_Weap_SniperRifles.Name.Title_Dahl.Title_Legendary_Pitchfork:AttributePresentationDefinition_8",
                "Fires 5 shots in shape of V. 2 Ammo per shot.",
                None,
                None,
                ),
            ("Invader",
                "GD_Weap_SniperRifles.Name.Title_Hyperion.Title_Legendary_Invader:AttributePresentationDefinition_8",
                "Fires a burst of 5 rounds when scoped.",
                None,
                None,
                ),
            ("Amigo Sincero",
                "GD_Anemone_Weap_SniperRifles.Name.Title.Title__Unique_Morde_Lt:AttributePresentationDefinition_8",
                "Damage ignores enemy shields, have mostly fixed parts.",
                None,
                None,
                ),
            ],
        'Unique': [
            ("Sloth",
                "GD_Weap_SniperRifles.Name.Title.Title__Unique_Sloth:AttributePresentationDefinition_8",
                "Increased damage and reduced bullet speed.",
                None,
                None,
                ),
            ("Trespasser",
                "GD_Weap_SniperRifles.Name.Title.Title__Unique_Trespasser:AttributePresentationDefinition_8",
                "Bypasses shields.",
                None,
                None,
                ),
            ("Buffalo",
                "GD_Weap_SniperRifles.Name.Title_Jakobs.Title_Jakobs_Buffalo:AttributePresentationDefinition_8",
                "<br/> Cannot spawn with a scope.",
                None,
                None,
                ),
            ("Pimpernel",
                "GD_Orchid_BossWeapons.Name.Title.Title__Unique_Pimpernel:AttributePresentationDefinition_8",
                "Projectile splits in 5 on hitting surface.",
                None,
                None,
                ),
            ("Morningstar",
                "GD_Weap_SniperRifles.Name.Title.Title__Unique_Morningstar:AttributePresentationDefinition_8",
                "Adds a short-lived 20% critical hit damage bonus for each critical hit. Speaks to your actions.",
                None,
                None,
                ),
            ("Longbow",
                "GD_Weap_SniperRifles.Name.Title.Title__Unique_Longbow:AttributePresentationDefinition_8",
                "Fires slow moving arrow, Always incendiary and without a scope, +150% Crit damage.",
                None,
                None,
                ),
            ("Cobra",
                "GD_Iris_Weapons.Name.Title.Title_Unique_Cobra:AttributePresentationDefinition_8",
                "Explosive splash.",
                None,
                None,
                ),
            ("Elephant Gun",
                "GD_Sage_Weapons.Name.Title.Title_Unique_ElephantGun:AttributePresentationDefinition_8",
                "Increased damage, fire rate. Reduced accuracy, reload, mag size. Always no scope.",
                None,
                None,
                ),
            ("Fremington's Edge",
                "GD_Weap_SniperRifles.Name.Title.Title__Unique_FremingtonsEdge:AttributePresentationDefinition_8",
                "Massive zoom, increase damage and accuracy. Crit bonus when zoomed.",
                None,
                None,
                ),
            ],
        'Moxxi': [
            ("Chere-Amie",
                "GD_Weap_SniperRifles.Name.Title.Title__Unique_Chere-amie:AttributePresentationDefinition_8",
                "Transfusions on hit and 2% lifesteal.",
                None,
                # BLCMM saves files in UTF-8, which BL2 doesn't actually understand, so for now I've got to avoid
                # "special" chars here, alas.  If BLCMM gets patched to write out latin1/iso-8859-1, I can get
                # rid of this override.
                'Je suis enchante. Ou est la bibliotheque?',
                ),
            ],
        'Effervescent': [
            ("Hot Mama",
                "GD_Anemone_Weapons.Name.Title.Title_Pearlescent_Chaude_Mama:AttributePresentationDefinition_8",
                "Always Incendiary. Bolt action fire rate. Fixed melee attachment.",
                None,
                None,
                ),
            ],
        }),
    ('Shields', DESC, {
        'Seraph': [
            ("Big Boom Blaster",
                "GD_Iris_SeraphItems.BigBoomBlaster.Iris_Seraph_Shield_Booster:AttributePresentationDefinition_0",
                "Boosters also regen 1 grenade and rocket ammo on pickup.",
                None,
                None,
                ),
            ("Pun-chee",
                "GD_Iris_SeraphItems.Pun-chee.Iris_Seraph_Shield_Pun-chee_Title:AttributePresentationDefinition_0",
                ON_CARD,
                None,
                None,
                ),
            ("Antagonist",
                "GD_Aster_Shields.Titles.Title_Antagonist:AttributePresentationDefinition_1",
                ON_CARD,
                None,
                None,
                ),
            ("Blockade",
                "GD_Aster_Shields.Titles.Title_Blockade:AttributePresentationDefinition_1",
                ON_CARD,
                None,
                None,
                ),
            ("Evolution",
                "GD_Orchid_RaidWeapons.Shield.Anshin.Orchid_Seraph_Anshin_Shield_Title:AttributePresentationDefinition_0",
                ON_CARD,
                None,
                None,
                ),
            ("Hoplite",
                "GD_Iris_SeraphItems.Hoplite.Iris_Seraph_Shield_Juggernaut:AttributePresentationDefinition_0",
                ON_CARD,
                None,
                None,
                ),
            ("Sponge",
                "GD_Iris_SeraphItems.Sponge.Iris_Seraph_Shield_Sponge_Title:AttributePresentationDefinition_0",
                ON_CARD,
                None,
                None,
                ),
            ],
        'Legendary': [
            ("Whisky Tango Foxtrot",
                "GD_Shields.Titles.Title_Booster04_BoosterShieldLegendary:AttributePresentationDefinition_0",
                "IED Boosters spawn 3 volleys of shock grenades, can self damage.",
                None,
                None,
                ),
            ("Transformer",
                "GD_Shields.Titles.Title_Absorption04_AbsorptionShieldLegendaryShock:AttributePresentationDefinition_0",
                "Shock damage recharges the shield.",
                None,
                None,
                ),
            ("The Cradle",
                "GD_Shields.Titles.Title_Standard05_Legendary:AttributePresentationDefinition_1",
                "Discarded shield releases an explosive nova",
                None,
                None,
                ),
            ("Black Hole",
                "GD_Shields.Titles.Title_ShockNova02_Singularity:AttributePresentationDefinition_0",
                "Shock nova blast also has a singularity effect.",
                None,
                None,
                ),
            ("Flame of the Firehawk",
                "GD_Shields.Titles.Title_FireNova02_Phoenix:AttributePresentationDefinition_0",
                ON_CARD,
                None,
                None,
                ),
            ("The Bee",
                "GD_Shields.Titles.Title_Impact05_Legendary:AttributePresentationDefinition_1",
                ON_CARD,
                None,
                None,
                ),
            ("Fabled Tortoise",
                "GD_Shields.Titles.Title_Juggernaut04_JuggernautLegendary:AttributePresentationDefinition_0",
                ON_CARD,
                None,
                None,
                ),
            ("Hide of Terramorphous",
                "GD_Shields.Titles.Title_Roid03_ThresherRaid:AttributePresentationDefinition_0",
                ON_CARD,
                None,
                None,
                ),
            ("Impaler",
                "GD_Shields.Titles.Title_CorrosiveSpike02_Legendary:AttributePresentationDefinition_0",
                ON_CARD,
                None,
                None,
                ),
            ("Neogenator",
                "GD_Shields.Titles.Title_Chimera04_ChimeraShieldLegendary:AttributePresentationDefinition_0",
                ON_CARD,
                None,
                None,
                ),
            ("Sham",
                "GD_Shields.Titles.Title_Absorption04_AbsorptionShieldLegendaryNormal:AttributePresentationDefinition_0",
                ON_CARD,
                None,
                None,
                ),
            ],
        'Unique': [
            ("Love Thumper",
                "GD_Shields.Titles.Title_Roid03_LoveThumper:AttributePresentationDefinition_1",
                "Does explosive nova on melee impact that deal friendly fire damage",
                None,
                None,
                ),
            ("Captain's Blade Manly Man",
                "GD_Orchid_Shields.Accessory.Accessory_Blade:AttributePresentationDefinition_6",
                "Wearer takes increased damage from elemental sources.",
                None,
                None,
                ),
            ("1340 Shield",
                "GD_Shields.Titles.Title_Absorption02_1340:AttributePresentationDefinition_0",
                "Unique voice module.",
                None,
                None,
                ),
            ("Pot O' Gold",
                "GD_Shields.Titles.Title_Booster04_BoosterShieldPotOGold:AttributePresentationDefinition_0",
                ON_CARD,
                None,
                None,
                ),
            ("Aequitas",
                "GD_Shields.Accessory.Title_Absorption03_Aequitas:AttributePresentationDefinition_0",
                ON_CARD,
                None,
                None,
                ),
            ("Deadly Bloom",
                "GD_Shields.Titles.Title_ExplosiveNova02_DeadlyBloom:AttributePresentationDefinition_1",
                ON_CARD,
                None,
                None,
                ),
            ("Order",
                "GD_Shields.Titles.Title_Roid05_Order:AttributePresentationDefinition_0",
                ON_CARD,
                None,
                None,
                ),
            ("Rough Rider",
                "GD_Sage_Shields.Accessory.Accessory_Buckler:AttributePresentationDefinition_5",
                ON_CARD,
                None,
                None,
                ),
            ],
        'Effervescent': [
            ("Retainer",
                "GD_Anemone_Shields.Titles.Title_Roid05_Order:AttributePresentationDefinition_0",
                "No roid bonus.",
                None,
                None,
                ),
            ("Easy Mode",
                "GD_Anemone_Shields.Titles.Title_ShockNova02_Singularity:AttributePresentationDefinition_0",
                ON_CARD,
                None,
                None,
                ),
            ],
        }),
    ('Grenade Mods', DESC, {
        'Legendary': [
            ("Bonus Package",
                "GD_GrenadeMods.Payload.Payload_BonusPackage:AttributePresentationDefinition_4",
                "Each child releases an extra child grenade.",
                None,
                None,
                ),
            ("Bouncing Bonny",
                "GD_GrenadeMods.Payload.Payload_BouncingBonny:AttributePresentationDefinition_4",
                "Releases child bouncing betty grenades.",
                None,
                None,
                ),
            ("Fastball",
                "GD_GrenadeMods.Delivery.Delivery_Fastball:AttributePresentationDefinition_4",
                "Extremely fast lob, bounces when it hits a surface.",
                None,
                None,
                ),
            ("Fire Bee",
                "GD_GrenadeMods.Title.Title_ExterminatorIncendiary:AttributePresentationDefinition_0",
                "Spits fire in a circle, launches small fire missiles.",
                None,
                None,
                ),
            ("Leech",
                "GD_GrenadeMods.Payload.Payload_Leech:AttributePresentationDefinition_4",
                "Transfusion healing effect.",
                None,
                None,
                ),
            ("Pandemic",
                "GD_GrenadeMods.Title.Title_ExterminatorCorrosive:AttributePresentationDefinition_0",
                "Launches 3 corrosive-DOT homing grenades on explosion.",
                None,
                None,
                ),
            ("Quasar",
                "GD_GrenadeMods.Payload.Payload_Quasar:AttributePresentationDefinition_4",
                "Largest singularity grenade, constant shock DOTs.",
                None,
                # Have to do an override here thanks to some deficiencies in FT/BLCMM Explorer's data introspection
                'E = mc^(OMG)/wtf',
                ),
            ("Rolling Thunder",
                "GD_GrenadeMods.Delivery.Delivery_RollingThunder:AttributePresentationDefinition_4",
                "Low arc, detonates on each bounce, will eventually explode as a MIRV.",
                None,
                None,
                ),
            ("Storm Front",
                "GD_GrenadeMods.Title.Title_ExterminatorShock:AttributePresentationDefinition_0",
                "Launches sticky child tesla grenades.",
                None,
                None,
                ),
            ("Nasty Surprise",
                "GD_GrenadeMods.Delivery.Delivery_NastySurprise:AttributePresentationDefinition_4",
                "Longbow delivery, will drop four child grenades enroute or at final destination.",
                None,
                None,
                ),
            ("Chain Lightning",
                "GD_Aster_GrenadeMods.Delivery.Delivery_ChainLightning:AttributePresentationDefinition_4",
                "Shoots lightning which explodes on impact and arcs to nearby targets.",
                None,
                None,
                ),
            ("Fire Storm",
                "GD_Aster_GrenadeMods.Delivery.Delivery_FireStorm:AttributePresentationDefinition_4",
                "Shoots fireball which explodes on impact and spawns four additional fireballs.",
                None,
                None,
                ),
            ],
        'Unique': [
            ("Breath of Terramorphous",
                "GD_GrenadeMods.Payload.Payload_FlameSpurt:AttributePresentationDefinition_4",
                "AOE, spawns child grenades which shoot geysers of flame.",
                None,
                None,
                ),
            ("Fireball",
                "GD_Aster_GrenadeMods.Delivery.Delivery_Fireball:AttributePresentationDefinition_4",
                "Fires a slow-moving fireball.",
                None,
                None,
                ),
            ("Fuster Cluck",
                "GD_GrenadeMods.Payload.Payload_FusterCluck:AttributePresentationDefinition_4",
                "Child grenades spawn in midair just after throwing.",
                None,
                None,
                ),
            ("Kiss of Death",
                "GD_GrenadeMods.Payload.Payload_KissOfDeath:AttributePresentationDefinition_4",
                "Grenade homes in and sticks to enemies, dealing DOTs.  Upon explosion, sounds out healing orbs.",
                None,
                None,
                ),
            ("Lightning Bolt",
                "GD_Aster_GrenadeMods.Delivery.Delivery_LightningBolt:AttributePresentationDefinition_4",
                "Shoots lightning straight forward and explodes on impact.",
                None,
                None,
                ),
            ("Magic Missile (ordinary)",
                "GD_Aster_GrenadeMods.Delivery.Delivery_MagicMissile:AttributePresentationDefinition_4",
                "Child grenades home in on enemies.",
                None,
                None,
                ),
            ("Magic Missile (rare)",
                "GD_Aster_GrenadeMods.Delivery.Delivery_MagicMissileRare:AttributePresentationDefinition_4",
                "Child grenades home in on enemies.",
                None,
                None,
                ),
            ("Captain Blade's Midnight Star",
                "GD_Orchid_GrenadeMods.Delivery.Delivery_Blade:AttributePresentationDefinition_1",
                "Child grenades are thrown towards player.",
                None,
                None,
                ),
            ("Contraband Sky Rocket",
                "GD_GrenadeMods.Delivery.Delivery_SkyRocket:AttributePresentationDefinition_0",
                "Flies upwards and releases a large burst of fireworks, increased damage.",
                None,
                None,
                ),
            ],
        'Seraph': [
            ("Crossfire",
                "GD_Iris_SeraphItems.Crossfire.Iris_Seraph_GrenadeMod_Crossfire:AttributePresentationDefinition_0",
                "Behaves like a bouncing betty, but also releases child grenades.",
                None,
                None,
                ),
            ("Meteor Shower",
                "GD_Iris_SeraphItems.MeteorShower.Iris_Seraph_GrenadeMod_MeteorShower_Title:AttributePresentationDefinition_0",
                "Child grenades have a high arc, and spawn an additional high-arc child each.",
                None,
                None,
                ),
            ("O-Negative",
                "GD_Iris_SeraphItems.ONegative.Iris_Seraph_GrenadeMod_ONegative:AttributePresentationDefinition_0",
                ON_CARD,
                None,
                None,
                ),
            ],
        'Effervescent': [
            ("Antifection",
                "GD_Anemone_GrenadeMods.Title.Title_ExterminatorIncendiary:AttributePresentationDefinition_0",
                "Spits fire in a circle, launches small fire missiles.",
                None,
                None,
                ),
            ("Electric Chair",
                "GD_Anemone_GrenadeMods.Title.Title_ExterminatorShock:AttributePresentationDefinition_0",
                "Launches sticky child tesla grenades along with an extra shock explosion.",
                None,
                None,
                ),
            ],
        }),
]

# Construct the mod
lines = []
lines.append('BL2')
lines.append('#<{}>'.format(mod_name))
lines.append('')
lines.append('    # {} v{}'.format(mod_name, mod_version))
lines.append('    # By Ezeith')
lines.append('    # (with some additions by Apocalyptech)')
lines.append('    #')
lines.append('    # The goal of this tool is mainly for players who don\'t know the game very well.')
lines.append('    # All weapons, grenades, and shields with red text will include extra text describing')
lines.append('    # the extra effects.  A lot of shields already have all their effects listed on the')
lines.append('    # card, so those will show up as "{}"'.format(ON_CARD))
lines.append('    #')
lines.append('    # Class Mods and Relics have been left alone, since all those list their effects')
lines.append('    # right on the card.')
lines.append('')

for (top_cat, attr_name, inner_cats) in sorted(mod_items):
    if attr_name not in valid_attrs:
        raise Exception('Invalid attribute specified: {}'.format(attr_name))
    lines.append('#<{}>'.format(top_cat))
    lines.append('')
    for (inner_cat, items) in sorted(inner_cats.items()):
        lines.append('#<{}>'.format(inner_cat))
        lines.append('')
        for (item_name, obj_name, extra_text, priority, override_text) in sorted(items):
            lines.append('#<{}>'.format(item_name))
            lines.append('')
            if priority is not None:
                lines.append('set {} BasePriority {}'.format(obj_name, priority))
                lines.append('')
            if override_text is None:
                item_struct = data.get_struct_by_full_object(obj_name)
                red_text = item_struct[attr_name]
            else:
                red_text = override_text
            if red_text != '' and extra_text != '':
                lines.append('set {} {} {} <font color="{}">[{}]</font>'.format(
                    obj_name,
                    attr_name, 
                    red_text.replace('(', '[').replace(')', ']'),
                    explanation_color,
                    extra_text.replace('(', '[').replace(')', ']'),
                    ))
                lines.append('')
            lines.append('#</{}>'.format(item_name))
            lines.append('')
        lines.append('#</{}>'.format(inner_cat))
        lines.append('')
    lines.append('#</{}>'.format(top_cat))
    lines.append('')

lines.append('#</{}>'.format(mod_name))
lines.append('')

# Write out to the file
mp.human_str_to_blcm_filename("\n".join(lines), output_filename)
print('Wrote mod to {}'.format(output_filename))
